version: '3.8'

services:
  app:
    build: .
    network_mode: host
    env_file: .env
    volumes:
      - ./firebase_service_account.json:/app/firebase_service_account.json:ro
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
