// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Project: e-money-b97f9
/// Sender:  714010609004
///
/// CATATAN: appId Android/iOS harus diambil dari google-services.json
/// yang diunduh dari Firebase Console setelah mendaftarkan app.
/// Jalankan `flutterfire configure` untuk menghasilkan file ini secara otomatis.
///
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRsMFg2QVCMv5rw-aNCrJ6HkKmZrkdMaA',
    appId: '1:714010609004:web:7e48d3cc934fb0d1271f49',
    messagingSenderId: '714010609004',
    projectId: 'e-money-b97f9',
    authDomain: 'e-money-b97f9.firebaseapp.com',
    storageBucket: 'e-money-b97f9.firebasestorage.app',
    measurementId: 'G-S5XQK0P3JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0q7qoZy0EEtbD5MKucQqgaOpIhJBW4Rg',
    appId: '1:714010609004:android:075cacdcd5cc0aba271f49',
    messagingSenderId: '714010609004',
    projectId: 'e-money-b97f9',
    storageBucket: 'e-money-b97f9.firebasestorage.app',
  );

  // Nilai ios appId di bawah ini harus diganti dengan nilai dari
  // GoogleService-Info.plist (unduh dari Firebase Console → Project Settings → iOS).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRsMFg2QVCMv5rw-aNCrJ6HkKmZrkdMaA',
    appId: '1:714010609004:ios:7e48d3cc934fb0d1271f49',
    messagingSenderId: '714010609004',
    projectId: 'e-money-b97f9',
    storageBucket: 'e-money-b97f9.firebasestorage.app',
    iosBundleId: 'com.kampus.dompetKampusGlobal',
  );
}
